#pragma once
#include <pebble.h>

// Mirror of the AppMessage schema in Plan section 6. The MESSAGE_KEY_* symbols
// themselves are generated by the SDK from package.json's messageKeys array;
// this header just documents the contract and defines the enums that ride
// inside the numeric keys.

// PHASE (uint8)
typedef enum {
  TM_PHASE_IDLE             = 0,
  TM_PHASE_PRINTING         = 1,
  TM_PHASE_CURING           = 2,
  TM_PHASE_LIFTING          = 3,
  TM_PHASE_PEELING          = 4,
  TM_PHASE_PAUSED           = 5,
  TM_PHASE_LOW_RESIN_PAUSE  = 6,
  TM_PHASE_FINISHED         = 7,
  TM_PHASE_CANCELED         = 8,
  TM_PHASE_POWER_LOSS       = 9,
  TM_PHASE_COUNT
} TmPhase;

// EVENT (uint8) - one-shot, phone-side derived, triggers a vibe on the watch.
typedef enum {
  TM_EVENT_NONE             = 0,
  TM_EVENT_FINISHED         = 1,
  TM_EVENT_CANCELED         = 2,
  TM_EVENT_LOW_RESIN_PAUSE  = 3,
  TM_EVENT_POWER_LOSS       = 4,
} TmEvent;

// CONN_STATE (uint8) - bridge health, so the watch can tell "no print running"
// apart from "the phone can't reach the printer".
typedef enum {
  TM_CONN_UNKNOWN    = 0,
  TM_CONN_UNCONFIGURED = 1,
  TM_CONN_CONNECTING = 2,
  TM_CONN_CONNECTED  = 3,
  TM_CONN_ERROR      = 4,
} TmConnState;

#define TM_PRINT_NAME_MAX 25   // 24 chars + NUL, truncated JS-side
#define TM_CONN_MSG_MAX   25

// No update in this many seconds => the on-watch data is flagged stale.
#define TM_STALE_AFTER_SEC 50
